/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesIndexRouteImport } from './routes/series/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsSlugRouteImport } from './routes/posts/$slug'
import { Route as SeriesSlugIndexRouteImport } from './routes/series/$slug/index'
import { Route as SeriesSlugPostSlugRouteImport } from './routes/series/$slug/$postSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesIndexRoute = SeriesIndexRouteImport.update({
  id: '/series/',
  path: '/series/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsSlugRoute = PostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugIndexRoute = SeriesSlugIndexRouteImport.update({
  id: '/series/$slug/',
  path: '/series/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugPostSlugRoute = SeriesSlugPostSlugRouteImport.update({
  id: '/series/$slug/$postSlug',
  path: '/series/$slug/$postSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/series/$slug/$postSlug': typeof SeriesSlugPostSlugRoute
  '/series/$slug/': typeof SeriesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts': typeof PostsIndexRoute
  '/series': typeof SeriesIndexRoute
  '/series/$slug/$postSlug': typeof SeriesSlugPostSlugRoute
  '/series/$slug': typeof SeriesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/posts/$slug': typeof PostsSlugRoute
  '/posts/': typeof PostsIndexRoute
  '/series/': typeof SeriesIndexRoute
  '/series/$slug/$postSlug': typeof SeriesSlugPostSlugRoute
  '/series/$slug/': typeof SeriesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts/$slug'
    | '/posts/'
    | '/series/'
    | '/series/$slug/$postSlug'
    | '/series/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts/$slug'
    | '/posts'
    | '/series'
    | '/series/$slug/$postSlug'
    | '/series/$slug'
  id:
    | '__root__'
    | '/'
    | '/posts/$slug'
    | '/posts/'
    | '/series/'
    | '/series/$slug/$postSlug'
    | '/series/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PostsSlugRoute: typeof PostsSlugRoute
  PostsIndexRoute: typeof PostsIndexRoute
  SeriesIndexRoute: typeof SeriesIndexRoute
  SeriesSlugPostSlugRoute: typeof SeriesSlugPostSlugRoute
  SeriesSlugIndexRoute: typeof SeriesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/': {
      id: '/series/'
      path: '/series'
      fullPath: '/series/'
      preLoaderRoute: typeof SeriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$slug': {
      id: '/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof PostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug/': {
      id: '/series/$slug/'
      path: '/series/$slug'
      fullPath: '/series/$slug/'
      preLoaderRoute: typeof SeriesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$slug/$postSlug': {
      id: '/series/$slug/$postSlug'
      path: '/series/$slug/$postSlug'
      fullPath: '/series/$slug/$postSlug'
      preLoaderRoute: typeof SeriesSlugPostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PostsSlugRoute: PostsSlugRoute,
  PostsIndexRoute: PostsIndexRoute,
  SeriesIndexRoute: SeriesIndexRoute,
  SeriesSlugPostSlugRoute: SeriesSlugPostSlugRoute,
  SeriesSlugIndexRoute: SeriesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './entry.router.ts'
import type { startInstance } from './entry.start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
